In [1]:
pip install numpy

In [2]:
import numpy as np

In [3]:
print(np.__version__)
 

1.19.2


In [4]:
# Creating Arrays
list=[1,2,3]
list

[1, 2, 3]

In [6]:
arr_list=np.array(list)
arr_list

array([1, 2, 3])

In [7]:
print(type(arr_list))

<class 'numpy.ndarray'>


In [9]:
arr_list=np.array([1,2,3,4])
arr_list

array([1, 2, 3, 4])

In [10]:
list1=[1,2,3]
list2=[4,5,6]
arr_list1=np.array([list1,list2])
arr_list1

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
list1=[1,2,3]
list2=[4,5,6]
list3=[7,8,9]
arr_list1=np.array([[list1,list2,list3]])
arr_list1

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [15]:
print(arr_list1.ndim)

3


In [17]:
# Numpy array attributes
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1.shape)
print(arr1.size)
print(arr1.dtype)
print(arr1.ndim)

(2, 3)
6
int32
2


In [19]:
arr2=np.array([1,2,3])
arr2

array([1, 2, 3])

In [20]:
print(arr2.shape)
print(arr2.size)
print(arr2.dtype)
print(arr2.ndim)

(3,)
3
int32
1


In [22]:
arr3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
arr3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [23]:
print(arr3.shape)
print(arr3.size)
print(arr3.dtype)
print(arr3.ndim)

(1, 3, 3)
9
int32
3


In [ ]:
# Array initilization method


In [26]:
#zero array
zero_arr=np.zeros((2,3))
zero_arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
#One array
one_arr=np.ones((2,4))
one_arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
# Full array
full_arr=np.full((3,2),5)
full_arr

array([[5, 5],
       [5, 5],
       [5, 5]])

In [29]:
#Identity matrix
id_arr=np.eye(3)
id_arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
#Empty array
print(np.empty(2))

[4.24399158e-314 8.48798317e-314]


In [31]:
# Evenly spaces array
print(np.arange(1,10,2))

[1 3 5 7 9]


In [33]:
#Specific number of equaly space values between a range
print(np.linspace(1,10,4))

[ 1.  4.  7. 10.]


In [35]:
#Random value array
r_arr=np.random.rand(3,2)
print(r_arr)

[[0.49601846 0.96745717]
 [0.40824076 0.28695497]
 [0.80141451 0.1314015 ]]


In [36]:
#Random value array--int
rint_arr=np.random.randint(1,100,(3,3))
print(rint_arr)

[[22 18 52]
 [74 38 11]
 [50 37 84]]


In [37]:
# Aray indexing
a=np.array([1,2,3,4,5,6])

In [38]:
print(a[0])

1


In [39]:
print(a[4])

5


In [40]:
#Slicing  array[start:stop:step]
print(a)


[1 2 3 4 5 6]


In [41]:
print(a[0:3])# stop element nit include

[1 2 3]


In [42]:
print(a[-3:])

[4 5 6]


In [43]:
print(a[-1:-3])

[]


In [44]:
print(a[1:4])

[2 3 4]


In [45]:
print(a[0::2]) # with step without stop

[1 3 5]


In [46]:
arr2=np.array([[1,2,3],[4,5,6]])

In [47]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
arr2[0]

array([1, 2, 3])

In [49]:
arr2[1]

array([4, 5, 6])

In [50]:
print(arr2[0][0])

1


In [51]:
print(arr2[0][1])

2


In [53]:
print(arr2[1])# 1d array

[4 5 6]


In [54]:
print(arr2[1:]) # 2d array

[[4 5 6]]


In [56]:
print(arr2)

[[1 2 3]
 [4 5 6]]


In [55]:
print(arr2[:,1])

[2 5]


In [57]:
print(arr2[1][1])

5


In [58]:
print(arr2[:,0])  # after , gives column

[1 4]


In [65]:
arr3=np.array([[[1,2,3,],[4,5,6],[7,8,9]]])
(arr3)

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [66]:
print(arr3[0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [67]:
print(arr3[0][2])

[7 8 9]


In [70]:
print(arr3[:,1])

[[4 5 6]]


In [71]:
print(arr1)

[[1 2 3]
 [4 5 6]]


In [77]:
array=np.array([1,2,3,4,5,6])

In [78]:
reshaped=array.reshape((6,1))
print(reshaped)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [79]:
reshaped2=array.reshape((2,3))

In [80]:
print(reshaped2)

[[1 2 3]
 [4 5 6]]


In [81]:
print(reshaped2.flatten())

[1 2 3 4 5 6]


In [ ]:
# Array Stacking(combining multiple array) and Splitting

In [82]:
a=np.array([1,2,3])
b=np.array([5,6,7])

print(np.vstack((a,b)))  #vertical Stacking
print(np.hstack((a,b)))  #horizontal stacking

[[1 2 3]
 [5 6 7]]
[1 2 3 5 6 7]


In [83]:
 c=np.array([[1,2,3],[4,5,6]])
    print(c)   

[[1 2 3]
 [4 5 6]]


In [86]:
split=np.hsplit(c,3) #horizontal splitting
for s in split:
    print(s)

[[1]
 [4]]
[[2]
 [5]]
[[3]
 [6]]


In [88]:
split=np.vsplit(c,2) #vertical splitting
print(split)

[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [ ]:
# Mathematical Operations on Array

In [89]:
print(a)

[1 2 3]


In [90]:
a=np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [91]:
print(a+25)

[26 27 28 29 30 31]


In [92]:
print(a-20)

[-19 -18 -17 -16 -15 -14]


In [93]:
print(a*5)

[ 5 10 15 20 25 30]


In [94]:
print(a/2)

[0.5 1.  1.5 2.  2.5 3. ]


In [95]:
b=np.array([1,4,9])
print(b)

[1 4 9]


In [96]:
print(np.square(b))

[ 1 16 81]


In [97]:
print(np.sqrt(b))

[1. 2. 3.]


In [98]:
print(np.sin(b))

[ 0.84147098 -0.7568025   0.41211849]


In [99]:
print(np.cos(b))

[ 0.54030231 -0.65364362 -0.91113026]


In [ ]:
Mathepatical opration on Multiple Array

In [106]:
a=np.array([1,2,3])
b=np.array([4,5,6])            

In [107]:
print(np.add(a,b))

[5 7 9]


In [108]:
print(np.subtract(a,b))

[-3 -3 -3]


In [111]:
print(np.multiply(a,b))

[ 4 10 18]


In [112]:
print(np.divide(a,b))

[0.25 0.4  0.5 ]


In [113]:
print(np.dot(a,b))  # dot product

32


In [115]:
t=np.array([[1,2,3],
          [4,5,6]])

print(t)
print(t.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
#Statitistical Functions

In [116]:
print(t)

[[1 2 3]
 [4 5 6]]


In [117]:
print(np.sum(t))

21


In [118]:
print(np.mean(t))

3.5


In [119]:
print(np.median(t))

3.5


In [120]:
print(np.std(t))

1.707825127659933


In [121]:
print(np.max(t))

6


In [122]:
print(np.min(t))

1


In [123]:
# Array Comparision
a=np.array([1,6,3])
b=np.array([5,6,7])
print(a)
print(b)

[1 6 3]
[5 6 7]


In [124]:
print(a==b)   # Comparing each elements
print(np.array_equal(a,b))  #comparing complete array

[False  True False]
False


In [ ]:
# Bradcasting

In [126]:
a=np.array([1,2,3,4,5])
b=np.array([5])
print(a+b)

[ 6  7  8  9 10]


In [128]:
c=np.array([[1,2,3],[4,5,6]])
d=np.array([11,22,33])
print(c+d)

[[12 24 36]
 [15 27 39]]


In [ ]:
# Handling with nan and inf

In [129]:
data1=np.array([1,2,np.nan,4,np.inf])
print(data1)

[ 1.  2. nan  4. inf]


In [130]:
print(np.isnan(data1))

[False False  True False False]


In [131]:
print(np.nan_to_num(data1))

[1.00000000e+000 2.00000000e+000 0.00000000e+000 4.00000000e+000
 1.79769313e+308]
